# Generated by Django 5.0.6 on 2024-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_status',
            field=models.BooleanField(default=False),
        ),
    ]
