# Generated by Django 5.0.6 on 2024-06-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_homework_homework_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Lesson',
        ),
    ]
