# Generated by Django 5.0.6 on 2024-06-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_homework_description_homework_homework_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks'),
        ),
    ]
